server:
  port: 8085
spring:
  rabbitmq:
    host: 192.168.18.130
    port: 5672
    username: admin
    password: admin
management:
#  endpoint:
#    shutdown:
#      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露actuator提供的各种接口，比如/actuator/refresh
